player-skin: true
rename-enabled: false
rename-item: 339
drop-chance: 50
death-types:  
  - PVP
  - ALL
items-required:
  - ANY
  - 276
debug-enabled: false
sneak-punch-info: true
zombie-heads:  
  drop-chance: 0
skeleton-heads:
  drop-chance: 0
creeper-heads:  
  drop-chance: 0