player-skin: true
drop-chance: 50
death-types:  
  - PVP
  - ALL
debug-enabled: false
sneak-punch-info: true
zombie-heads:  
  drop-chance: 0
skeleton-heads:
  drop-chance: 0
creeper-heads:  
  drop-chance: 0